"""adding third-tear columns

Revision ID: 6b27ce715525
Revises: 71ee8dcd967e
Create Date: 2025-11-27 23:17:42.448192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b27ce715525'
down_revision: Union[str, Sequence[str], None] = '71ee8dcd967e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('correct_ans', sa.String(), nullable=False),
    sa.Column('incorrect_1', sa.String(), nullable=True),
    sa.Column('incorrect_2', sa.String(), nullable=True),
    sa.Column('incorrect_3', sa.String(), nullable=True),
    sa.Column('incorrect_4', sa.String(), nullable=True),
    sa.Column('incorrect_5', sa.String(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('submission_status', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_table('submission')
    op.drop_table('task')
    # ### end Alembic commands ###
