"""add_cascade_delete_to_quiz_course_fk

Revision ID: 8e37d62ee9de
Revises: 6b27ce715525
Create Date: 2026-01-28 15:22:35.539739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e37d62ee9de'
down_revision: Union[str, Sequence[str], None] = '6b27ce715525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('quiz_course_id_fkey'), 'quiz', type_='foreignkey')
    op.create_foreign_key(None, 'quiz', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_course_id_fkey'), 'quiz', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###
